name: dotnet Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ["6.0.x"]


    steps:
      - uses: actions/checkout@v3
      - name: Setup Dotnet Content
        uses: actions/checkout@v3
        with:
          dotnet-version: "6.0.x"
      - name: Install Deps
        run: dotnet restore

      - name: Gen Package
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tage_name: "release-v1-2023"
          release_name: "Release WISSAL FORMATION 2023"
          draft: false
          prerelease: false      
